language: cpp

dist: bionic
sudo: required

compiler:
  - clang

before_install: 
  - sudo apt-get update
  - sudo apt-get install libsdl2-dev libsdl2-mixer-dev libegl1-mesa-dev libgles2-mesa-dev

before_script: mkdir obj
script: 
  - make
  - cd Run
  - git clone --depth=50 https://github.com/OpenFodder/tests.git Tests
  - ./OpenFodder --unit-test-headless