#include "stdafx.hpp"

struct sRecruit mRecruits[360] =
{
  { "JOOLS ", '\x02', '\xFF', '\x04' },
  { "JOPS  ", '\x02', '\xFF', '\x06' },
  { "STOO  ", '\x02', '\xFF', '\0' },
  { "RJ    ", '\x02', '\xFF', '\0' },
  { "UBIK  ", '\x02', '\xFF', '\x01' },
  { "CJ    ", '\x02', '\xFF', '\0' },
  { "CHRIS ", '\x02', '\xFF', '\0' },
  { "PETE  ", '\x02', '\xFF', '\0' },
  { "TADGER", '\x03', '\xFF', '\x03' },
  { "HECTOR", '\x02', '\xFF', '\0' },
  { "ELROY ", '\x02', '\xFF', '\0' },
  { "SOFTY ", '\x02', '\xFF', '\0' },
  { "MAC   ", '\x02', '\xFF', '\0' },
  { "BOMBER", '\x02', '\xFF', '\0' },
  { "STAN  ", '\x02', '\xFF', '\0' },
  { "TOSH  ", '\x02', '\xFF', '\0' },
  { "BRAINS", '\x02', '\xFF', '\x01' },
  { "NORM  ", '\x02', '\xFF', '\0' },
  { "BUSTER", '\x02', '\xFF', '\0' },
  { "SPIKE ", '\x02', '\xFF', '\0' },
  { "BROWNY", '\x02', '\xFF', '\0' },
  { "MURPHY", '\x02', '\xFF', '\a' },
  { "KILLER", '\x02', '\xFF', '\0' },
  { "ABDUL ", '\x02', '\xFF', '\0' },
  { "SPOTTY", '\x02', '\xFF', '\0' },
  { "GOOFY ", '\x02', '\xFF', '\0' },
  { "DONALD", '\x02', '\xFF', '\x05' },
  { "WINDY ", '\x02', '\xFF', '\0' },
  { "NIFTA ", '\x02', '\xFF', '\0' },
  { "DENZIL", '\x02', '\xFF', '\0' },
  { "CEDRIC", '\x02', '\xFF', '\0' },
  { "ALF   ", '\x02', '\xFF', '\0' },
  { "MARTY ", '\x02', '\xFF', '\0' },
  { "CECIL ", '\x02', '\xFF', '\0' },
  { "WALLY ", '\x03', '\xFF', '\0' },
  { "DONG  ", '\x02', '\xFF', '\0' },
  { "JASON ", '\x02', '\xFF', '\0' },
  { "ROY   ", '\x02', '\xFF', '\0' },
  { "PEEWEE", '\x02', '\xFF', '\0' },
  { "ARNIE ", '\x02', '\xFF', '\x03' },
  { "LOFTY ", '\x02', '\xFF', '\0' },
  { "TUBBY ", '\x02', '\xFF', '\0' },
  { "PORKY ", '\x02', '\xFF', '\0' },
  { "NORRIS", '\x02', '\xFF', '\0' },
  { "BUGSY ", '\x02', '\xFF', '\0' },
  { "GREG  ", '\x02', '\xFF', '\0' },
  { "GUS   ", '\x02', '\xFF', '\0' },
  { "GINGER", '\x02', '\xFF', '\0' },
  { "EDDY  ", '\x02', '\xFF', '\0' },
  { "STEVE ", '\x02', '\xFF', '\0' },
  { "HUGO  ", '\x02', '\xFF', '\0' },
  { "ZIPPY ", '\x02', '\xFF', '\0' },
  { "SONNY ", '\x02', '\xFF', '\0' },
  { "WILLY ", '\x02', '\xFF', '\0' },
  { "MARIO ", '\x02', '\xFF', '\0' },
  { "LUIGI ", '\x02', '\xFF', '\0' },
  { "BO    ", '\x02', '\xFF', '\0' },
  { "JOHAN ", '\x02', '\xFF', '\0' },
  { "COLIN ", '\x02', '\xFF', '\0' },
  { "RUBY  ", '\x02', '\xFF', '\0' },
  { "MORGAN", '\x02', '\xFF', '\0' },
  { "REG   ", '\x02', '\xFF', '\0' },
  { "PETER ", '\x02', '\xFF', '\0' },
  { "BRETT ", '\x02', '\xFF', '\0' },
  { "MATT  ", '\x02', '\xFF', '\0' },
  { "VIC   ", '\x02', '\xFF', '\0' },
  { "HUT   ", '\x02', '\xFF', '\0' },
  { "BUD   ", '\x02', '\xFF', '\0' },
  { "BRAD  ", '\x02', '\xFF', '\0' },
  { "ASHLEY", '\x02', '\xFF', '\0' },
  { "LES   ", '\x02', '\xFF', '\0' },
  { "REX   ", '\x02', '\xFF', '\0' },
  { "LOUIS ", '\x02', '\xFF', '\0' },
  { "PEDRO ", '\x02', '\xFF', '\0' },
  { "MARCO ", '\x02', '\xFF', '\0' },
  { "LEON  ", '\x02', '\xFF', '\0' },
  { "ALI   ", '\x02', '\xFF', '\0' },
  { "TYSON ", '\x02', '\xFF', '\0' },
  { "TIGER ", '\x02', '\xFF', '\0' },
  { "FRANK ", '\x02', '\xFF', '\0' },
  { "REUBEN", '\x02', '\xFF', '\0' },
  { "LEYTON", '\x02', '\xFF', '\0' },
  { "JOSH  ", '\x02', '\xFF', '\0' },
  { "JUDAS ", '\x02', '\xFF', '\0' },
  { "AJ    ", '\x02', '\xFF', '\0' },
  { "LEX   ", '\x02', '\xFF', '\0' },
  { "BUTCH ", '\x02', '\xFF', '\0' },
  { "BISON ", '\x02', '\xFF', '\0' },
  { "GARY  ", '\x02', '\xFF', '\0' },
  { "LUTHER", '\x02', '\xFF', '\0' },
  { "KERMIT", '\x02', '\xFF', '\0' },
  { "BRIAN ", '\x02', '\xFF', '\0' },
  { "RAY   ", '\x02', '\xFF', '\0' },
  { "FREAK ", '\x02', '\xFF', '\0' },
  { "LEROY ", '\x02', '\xFF', '\0' },
  { "LEE   ", '\x02', '\xFF', '\0' },
  { "BANJO ", '\x02', '\xFF', '\0' },
  { "BEAKER", '\x02', '\xFF', '\0' },
  { "BASIL ", '\x02', '\xFF', '\0' },
  { "BONZO ", '\x02', '\xFF', '\0' },
  { "KELVIN", '\x02', '\xFF', '\0' },
  { "RONNIE", '\x02', '\xFF', '\0' },
  { "RUPERT", '\x02', '\xFF', '\0' },
  { "ROO   ", '\x02', '\xFF', '\0' },
  { "DAN   ", '\x02', '\xFF', '\0' },
  { "BASHER", '\x02', '\xFF', '\0' },
  { "RONNIE", '\x02', '\xFF', '\0' },
  { "LUCKY ", '\x02', '\xFF', '\0' },
  { "DON   ", '\x02', '\xFF', '\0' },
  { "TOMMY ", '\x02', '\xFF', '\0' },
  { "EDDIE ", '\x02', '\xFF', '\0' },
  { "CYNIC ", '\x02', '\xFF', '\0' },
  { "BLOND ", '\x02', '\xFF', '\0' },
  { "PADDY ", '\x02', '\xFF', '\0' },
  { "ARNOLD", '\x02', '\xFF', '\0' },
  { "TONY  ", '\x02', '\xFF', '\0' },
  { "TEDDY ", '\x02', '\xFF', '\0' },
  { "DOM   ", '\x02', '\xFF', '\0' },
  { "THEO  ", '\x02', '\xFF', '\0' },
  { "MARTIN", '\x02', '\xFF', '\0' },
  { "CHUNKY", '\x02', '\xFF', '\0' },
  { "JON   ", '\x02', '\xFF', '\0' },
  { "BEN   ", '\x02', '\xFF', '\0' },
  { "GIRLY ", '\x02', '\xFF', '\0' },
  { "JULIAN", '\x02', '\xFF', '\0' },
  { "GARY  ", '\x02', '\xFF', '\0' },
  { "PIZZA ", '\x02', '\xFF', '\0' },
  { "MARK  ", '\x02', '\xFF', '\0' },
  { "CIARAN", '\x02', '\xFF', '\0' },
  { "JOCK  ", '\x02', '\xFF', '\0' },
  { "GRAVY ", '\x02', '\xFF', '\0' },
  { "TRENDY", '\x02', '\xFF', '\0' },
  { "NEIL  ", '\x02', '\xFF', '\0' },
  { "DEREK ", '\x02', '\xFF', '\0' },
  { "ED    ", '\x02', '\xFF', '\0' },
  { "STEVE ", '\x02', '\xFF', '\0' },
  { "BIFF  ", '\x02', '\xFF', '\0' },
  { "STEVE ", '\x02', '\xFF', '\0' },
  { "PAUL  ", '\x02', '\xFF', '\0' },
  { "STUART", '\x02', '\xFF', '\0' },
  { "RANDY ", '\x02', '\xFF', '\0' },
  { "LORETA", '\x02', '\xFF', '\0' },
  { "SUZIE ", '\x02', '\xFF', '\0' },
  { "PUMPY ", '\x02', '\xFF', '\0' },
  { "URMER ", '\x02', '\xFF', '\0' },
  { "BUNNY ", '\x02', '\xFF', '\0' },
  { "ADEY  ", '\x02', '\xFF', '\0' },
  { "PEPPER", '\x02', '\xFF', '\0' },
  { "BEEFY ", '\x02', '\xFF', '\0' },
  { "HARRY ", '\x02', '\xFF', '\0' },
  { "TINY  ", '\x02', '\xFF', '\0' },
  { "HOWARD", '\x02', '\xFF', '\0' },
  { "MORRIS", '\x02', '\xFF', '\0' },
  { "THOR  ", '\x02', '\xFF', '\0' },
  { "REV   ", '\x02', '\xFF', '\0' },
  { "DUKE  ", '\x02', '\xFF', '\0' },
  { "SHORTY", '\x02', '\xFF', '\0' },
  { "MICKY ", '\x02', '\xFF', '\0' },
  { "CHAS  ", '\x02', '\xFF', '\0' },
  { "MELONY", '\x02', '\xFF', '\0' },
  { "CRAIG ", '\x02', '\xFF', '\0' },
  { "SIDNEY", '\x02', '\xFF', '\0' },
  { "PARSON", '\x02', '\xFF', '\0' },
  { "ROWAN ", '\x02', '\xFF', '\0' },
  { "SMELLY", '\x02', '\xFF', '\0' },
  { "DOK   ", '\x02', '\xFF', '\0' },
  { "STEW  ", '\x02', '\xFF', '\0' },
  { "DONALD", '\x02', '\xFF', '\0' },
  { "ADRIAN", '\x02', '\xFF', '\0' },
  { "PAT   ", '\x02', '\xFF', '\0' },
  { "ICEMAN", '\x02', '\xFF', '\0' },
  { "GOOSE ", '\x02', '\xFF', '\0' },
  { "DIPPY ", '\x02', '\xFF', '\0' },
  { "VIV   ", '\x02', '\xFF', '\0' },
  { "SI    ", '\x02', '\xFF', '\0' },
  { "BUNTY ", '\x02', '\xFF', '\0' },
  { "NOEL  ", '\x02', '\xFF', '\0' },
  { "BONO  ", '\x02', '\xFF', '\0' },
  { "EDGE  ", '\x02', '\xFF', '\0' },
  { "ROBBIE", '\x02', '\xFF', '\0' },
  { "SEAN  ", '\x02', '\xFF', '\0' },
  { "MILES ", '\x02', '\xFF', '\0' },
  { "JIMI  ", '\x02', '\xFF', '\0' },
  { "GORDON", '\x02', '\xFF', '\0' },
  { "VAL   ", '\x02', '\xFF', '\0' },
  { "HOBO  ", '\x02', '\xFF', '\0' },
  { "FUNGUS", '\x02', '\xFF', '\0' },
  { "JR    ", '\x02', '\xFF', '\0' },
  { "LAMPY ", '\x02', '\xFF', '\0' },
  { "MARCUS", '\x02', '\xFF', '\0' },
  { "PELE  ", '\x02', '\xFF', '\0' },
  { "HUBERT", '\x02', '\xFF', '\0' },
  { "JAMES ", '\x02', '\xFF', '\0' },
  { "TIM   ", '\x02', '\xFF', '\0' },
  { "SAUL  ", '\x02', '\xFF', '\0' },
  { "ANDY  ", '\x02', '\xFF', '\0' },
  { "ALF   ", '\x02', '\xFF', '\0' },
  { "SILKY ", '\x02', '\xFF', '\0' },
  { "SIMON ", '\x02', '\xFF', '\0' },
  { "HANDY ", '\x02', '\xFF', '\0' },
  { "SID   ", '\x02', '\xFF', '\0' },
  { "GEORGE", '\x02', '\xFF', '\0' },
  { "JOFF  ", '\x02', '\xFF', '\0' },
  { "BARRY ", '\x02', '\xFF', '\0' },
  { "DICK  ", '\x02', '\xFF', '\0' },
  { "GIL   ", '\x02', '\xFF', '\0' },
  { "NICK  ", '\x02', '\xFF', '\0' },
  { "TED   ", '\x02', '\xFF', '\0' },
  { "PHIL  ", '\x02', '\xFF', '\0' },
  { "WOODY ", '\x02', '\xFF', '\0' },
  { "WYNN  ", '\x02', '\xFF', '\0' },
  { "ALAN  ", '\x02', '\xFF', '\0' },
  { "PIP   ", '\x02', '\xFF', '\0' },
  { "MICKEY", '\x02', '\xFF', '\0' },
  { "JUSTIN", '\x02', '\xFF', '\0' },
  { "KARL  ", '\x02', '\xFF', '\0' },
  { "MADDOG", '\x02', '\xFF', '\0' },
  { "HORACE", '\x02', '\xFF', '\0' },
  { "HAROLD", '\x02', '\xFF', '\0' },
  { "GAZZA ", '\x02', '\xFF', '\0' },
  { "SPIV  ", '\x02', '\xFF', '\0' },
  { "FOXY  ", '\x02', '\xFF', '\0' },
  { "NED   ", '\x02', '\xFF', '\0' },
  { "BAZIL ", '\x02', '\xFF', '\0' },
  { "OLIVER", '\x02', '\xFF', '\0' },
  { "RETT  ", '\x02', '\xFF', '\0' },
  { "SCOT  ", '\x02', '\xFF', '\0' },
  { "DARREN", '\x02', '\xFF', '\0' },
  { "EDWIN ", '\x02', '\xFF', '\0' },
  { "MOSES ", '\x02', '\xFF', '\0' },
  { "NOAH  ", '\x02', '\xFF', '\0' },
  { "SETH  ", '\x02', '\xFF', '\0' },
  { "HARVEY", '\x02', '\xFF', '\0' },
  { "MARY  ", '\x02', '\xFF', '\0' },
  { "PILOT ", '\x02', '\xFF', '\0' },
  { "MCBETH", '\x02', '\xFF', '\0' },
  { "MCDUFF", '\x02', '\xFF', '\0' },
  { "BELLY ", '\x02', '\xFF', '\0' },
  { "MATHEW", '\x02', '\xFF', '\0' },
  { "MARK  ", '\x02', '\xFF', '\0' },
  { "LUKE  ", '\x02', '\xFF', '\0' },
  { "JOHN  ", '\x02', '\xFF', '\0' },
  { "ASLAM ", '\x02', '\xFF', '\0' },
  { "HAM   ", '\x02', '\xFF', '\0' },
  { "SHEM  ", '\x02', '\xFF', '\0' },
  { "JOSHUA", '\x02', '\xFF', '\0' },
  { "JACOB ", '\x02', '\xFF', '\0' },
  { "ESAW  ", '\x02', '\xFF', '\0' },
  { "OMAR  ", '\x02', '\xFF', '\0' },
  { "SAUL  ", '\x02', '\xFF', '\0' },
  { "ENOCH ", '\x02', '\xFF', '\0' },
  { "OBADIA", '\x02', '\xFF', '\0' },
  { "DANIEL", '\x02', '\xFF', '\0' },
  { "SAMUEL", '\x02', '\xFF', '\0' },
  { "BEN   ", '\x02', '\xFF', '\0' },
  { "ROBBO ", '\x02', '\xFF', '\0' },
  { "JOEBED", '\x02', '\xFF', '\0' },
  { "ISMAEL", '\x02', '\xFF', '\0' },
  { "ISREAL", '\x02', '\xFF', '\0' },
  { "ISABEL", '\x02', '\xFF', '\0' },
  { "ISARAT", '\x02', '\xFF', '\0' },
  { "MONK  ", '\x02', '\xFF', '\0' },
  { "BLIP  ", '\x02', '\xFF', '\0' },
  { "BACON ", '\x02', '\xFF', '\0' },
  { "DANUBE", '\x02', '\xFF', '\0' },
  { "FRIEND", '\x02', '\xFF', '\0' },
  { "DARRYL", '\x02', '\xFF', '\0' },
  { "IZZY  ", '\x02', '\xFF', '\0' },
  { "CROSBY", '\x02', '\xFF', '\0' },
  { "STILLS", '\x02', '\xFF', '\0' },
  { "NASH  ", '\x02', '\xFF', '\0' },
  { "YOUNG ", '\x02', '\xFF', '\0' },
  { "CHEESE", '\x02', '\xFF', '\0' },
  { "SALAMI", '\x02', '\xFF', '\0' },
  { "PRAWN ", '\x02', '\xFF', '\0' },
  { "RADISH", '\x02', '\xFF', '\0' },
  { "EGBERT", '\x02', '\xFF', '\0' },
  { "EDWY  ", '\x02', '\xFF', '\0' },
  { "EDGAR ", '\x02', '\xFF', '\0' },
  { "EDWIN ", '\x02', '\xFF', '\0' },
  { "EDRED ", '\x02', '\xFF', '\0' },
  { "EGGPIE", '\x02', '\xFF', '\0' },
  { "BROS  ", '\x02', '\xFF', '\0' },
  { "CAKEY ", '\x02', '\xFF', '\0' },
  { "ZIGGY ", '\x02', '\xFF', '\0' },
  { "ALFRED", '\x02', '\xFF', '\0' },
  { "SIGGY ", '\x02', '\xFF', '\0' },
  { "HILDA ", '\x02', '\xFF', '\0' },
  { "SNELL ", '\x02', '\xFF', '\0' },
  { "SPARKS", '\x02', '\xFF', '\0' },
  { "ROB   ", '\x02', '\xFF', '\0' },
  { "TOPCAT", '\x02', '\xFF', '\0' },
  { "BENNY ", '\x02', '\xFF', '\0' },
  { "DIBBLE", '\x02', '\xFF', '\0' },
  { "BENKER", '\x02', '\xFF', '\0' },
  { "DOSEY ", '\x02', '\xFF', '\0' },
  { "BEAKY ", '\x02', '\xFF', '\0' },
  { "JOIST ", '\x02', '\xFF', '\0' },
  { "PIVOT ", '\x02', '\xFF', '\0' },
  { "TREE  ", '\x02', '\xFF', '\0' },
  { "BUSH  ", '\x02', '\xFF', '\0' },
  { "GRASS ", '\x02', '\xFF', '\0' },
  { "SEEDY ", '\x02', '\xFF', '\0' },
  { "TIN   ", '\x02', '\xFF', '\0' },
  { "ROLLO ", '\x02', '\xFF', '\0' },
  { "ZIPPO ", '\x02', '\xFF', '\0' },
  { "NANCY ", '\x02', '\xFF', '\0' },
  { "LARRY ", '\x02', '\xFF', '\0' },
  { "IGGY  ", '\x02', '\xFF', '\0' },
  { "NIGEL ", '\x02', '\xFF', '\0' },
  { "JAMIE ", '\x02', '\xFF', '\0' },
  { "JESSE ", '\x02', '\xFF', '\0' },
  { "LEO   ", '\x02', '\xFF', '\0' },
  { "VIRGO ", '\x02', '\xFF', '\0' },
  { "GARTH ", '\x02', '\xFF', '\0' },
  { "FIDEL ", '\x02', '\xFF', '\0' },
  { "IDI   ", '\x02', '\xFF', '\0' },
  { "CHE   ", '\x02', '\xFF', '\0' },
  { "JOHNNY", '\x02', '\xFF', '\0' },
  { "AMBER ", '\x02', '\xFF', '\0' },
  { "LAIRY ", '\x02', '\xFF', '\0' },
  { "LARDO ", '\x02', '\xFF', '\0' },
  { "TONY  ", '\x02', '\xFF', '\0' },
  { "WOODY ", '\x02', '\xFF', '\0' },
  { "CLIFF ", '\x02', '\xFF', '\0' },
  { "FESTER", '\x02', '\xFF', '\0' },
  { "JETHRO", '\x02', '\xFF', '\0' },
  { "JIMBOB", '\x02', '\xFF', '\0' },
  { "DECLAN", '\x02', '\xFF', '\0' },
  { "NEIL  ", '\x02', '\xFF', '\0' },
  { "HICKEY", '\x02', '\xFF', '\0' },
  { "CHOCCO", '\x02', '\xFF', '\0' },
  { "GOCH  ", '\x02', '\xFF', '\0' },
  { "PABLO ", '\x02', '\xFF', '\0' },
  { "RENOIR", '\x02', '\xFF', '\0' },
  { "ROLF  ", '\x02', '\xFF', '\0' },
  { "DALI  ", '\x02', '\xFF', '\0' },
  { "MONET ", '\x02', '\xFF', '\0' },
  { "MANET ", '\x02', '\xFF', '\0' },
  { "GAUGIN", '\x02', '\xFF', '\0' },
  { "CHAGAL", '\x02', '\xFF', '\0' },
  { "KID   ", '\x02', '\xFF', '\0' },
  { "HULLY ", '\x02', '\xFF', '\0' },
  { "ROBERT", '\x02', '\xFF', '\0' },
  { "PIERS ", '\x02', '\xFF', '\0' },
  { "RAITH ", '\x02', '\xFF', '\0' },
  { "JEEVES", '\x02', '\xFF', '\0' },
  { "PASTER", '\x02', '\xFF', '\0' },
  { "GINAN ", '\x02', '\xFF', '\0' },
  { "DEITER", '\x02', '\xFF', '\0' },
  { "DENI  ", '\x02', '\xFF', '\0' },
  { "ZARK  ", '\x02', '\xFF', '\0' },
  { "WIZKID", '\x02', '\xFF', '\0' },
  { "WIZARD", '\x02', '\xFF', '\0' },
  { "IAIN  ", '\x02', '\xFF', '\0' },
  { "KITTEN", '\x02', '\xFF', '\0' },
  { "GONNER", '\x02', '\xFF', '\0' },
  { "WASTER", '\x02', '\xFF', '\0' },
  { "LOSER ", '\x02', '\xFF', '\0' },
  { "FODDER", '\x02', '\xFF', '\0' }
};
